#if !defined(AFX_RDOERRORS_H__BAD271D9_9804_11D1_9504_444553540000__INCLUDED_)
#define AFX_RDOERRORS_H__BAD271D9_9804_11D1_9504_444553540000__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
#include <afxdisp.h>

class CrdoError;

/////////////////////////////////////////////////////////////////////////////
// CrdoErrors wrapper class

class CrdoErrors : public COleDispatchDriver
{
public:
	CrdoErrors() {}		// Calls COleDispatchDriver default constructor
	CrdoErrors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoErrors(const CrdoErrors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CrdoError GetItem(const VARIANT& Index);
	void Clear();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOERRORS_H__BAD271D9_9804_11D1_9504_444553540000__INCLUDED_)
